import "./globals.css";

export const metadata = {
  title: "Trello clone",
  description: "Generated by Diego Suarez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
